#ifndef _DEFAULTS_
#define _DEFAULTS_

#define STRING_LENGTH 50
#define STRING_MESSAGE_LENGTH 150
#define STRING_JSON_LENGTH 200
#define JSON_DEFAULT_LONG_BUFFER_LENGTH 1024
#define JSON_DEFAULT_BUFFER_LENGTH 100

#endif